### PR TITLE
fixed issue 192:fixed geolocate control bug

### PR DESCRIPTION
**Pull request by sudoStatus200**
Hi @xintongxia ,
I have updated my PR after running `npm run lint fix`.

Thanks,

### CODE REVIEW

**Comment by xintongxia** [comment]
Thanks. Build is still failing, based on the error message, could you run `yarn upgrade` and update the PR? 

I think you can accumulate your changes in the same PR.

**Comment by sudoStatus200** [comment]
@xintongxia  Hi ,
We are using react-map-gl in our code and we need to fix this issue real quick. 
In my local browser test is failing maybe that's why travis CI test also failing.

Can you solve this real quick or merge this PR if possible? I am very busy that's why not getting time to fix that failed browser test.
Thanks,

**Comment by sudoStatus200** [comment]
@xintongxia  
draw polygon example  using @turf/area and react-map-gl-draw packages that are not present in package.json of whole project, thats why npm run start was also causing problem.After installing them npm run start runs fine but now test are failing. So I think this issue are complete different issue then the one that this PR trying to solve.

**Comment by xintongxia** [comment]
@sudoStatus200 I fixed the build issue. Could you rebase with master and resolve conflicts? Then we can merge your fixes into master.

**Comment by sudoStatus200** [comment]
@xintongxia 
I pulled cod from this master and fixed yarn.lock merge conflict in favor of yours change but it is still failing

**Pull request merged**
