### PR TITLE
WIP Remove immutable / use mapbox style diffing

### PR DESCRIPTION
**Pull request by vicapow**
Style diffing using mapbox-gl-style-spec still has some issues with flikr.

http://www.giphy.com/gifs/xULW8EmfshppodKWwU

### CODE REVIEW

**Comment by vicapow** [comment]
Whoops. I didn't see https://github.com/uber/react-map-gl/pull/433/files already exists

**Comment by Pessimistress** [comment]
@vicapow ideally we could keep immutable support but no longer require it for diffing. Worst case we can just cast it to a plain JS object.

**Comment by vicapow** [comment]
Makes sense. From the best I can tell this diff still maintains support for immutable but removes mentions to it.

**Comment by ibgreen** [comment]
@vicapow Looks like there is some good stuff here that wasn't covered in @Pessimistress PR. Rebase and repost?

**Pull request closed without merging**
