### PR TITLE
Upgrade to mapbox 0.44

### PR DESCRIPTION
**Pull request by ibgreen**
Also fixes deck.gl overlay example and verifies that 0.44 still renders in sync with deck.gl.

### CODE REVIEW

**Comment by ibgreen** [comment]
@vicapow @georgios-uber FYI

**Comment by ibgreen** [comment]
Fixes #458

**Comment by vicapow** [comment]
Nice!

**Comment by ibgreen** [comment]
> Website is broken. Can you separate the react version bump to another PR?

I made an attempt to fix the website instead, let me know.

**Pull request merged**
