### PR TITLE
Adds in touch support

### PR DESCRIPTION
**Pull request by cammanderson**
This pull request adds in support for touch events. This allows touch devices to pan in maps.

### CODE REVIEW

**Comment by ibgreen** [comment]
@cammanderson This looks great, would love to merge this PR. To do that, you would have to be registered as an [Uber open source contributor](https://docs.google.com/a/uber.com/forms/d/e/1FAIpQLSfu-DmpJD5wYYUOxY50noHF9BWJwDbV0d2W1w45oEIbIx72RQ/viewform).

If that is acceptable, let me know and I will merge and publish this asap.

**Comment by cammanderson** [comment]
Thanks @ibgreen :-)

That's done!

**Comment by ibgreen** [comment]
Touch support published as 1.5.0
@cammanderson @gnavvy @Pessimistress @philogb

**Comment by cammanderson** [comment]
Cheers :-)

**Pull request merged**
