### PR TITLE
Provide static browser/node targets

### PR DESCRIPTION
**Pull request by TrySound**
Ref https://github.com/uber/react-map-gl/issues/557 https://github.com/uber-web/mjolnir.js/pull/22

### CODE REVIEW

**Comment by TrySound** [comment]
Can we publish then major mjolnir release?

**Comment by TrySound** [comment]
So can this be merged? I will start working on rollup builds

**Comment by Pessimistress** [comment]
@TrySound do we need to update the mjolnir.js dependency?

**Comment by TrySound** [comment]
Done

**Comment by digitalkaoz** [comment]
yes, a merge and a prelease would be nice :)

**Comment by TrySound** [comment]
@ibgreen @Pessimistress I have a few ideas how to improve the size of this library. Will start working on it after merge of this PR.

**Comment by Pessimistress** [comment]
Published 4.0.0-alpha.2

**Comment by digitalkaoz** [comment]
@Pessimistress @TrySound i get this error now:

```
node_modules/react-map-gl/dist/esm/components/static-map.js

Module not found: Can't resolve '../utils/mapboxgl' in 'node_modules/react-map-gl/dist/esm/components
```

but its there :/

```js
export default null;
//# sourceMappingURL=mapboxgl.js.map
```

so whats wrong here?

**Comment by TrySound** [comment]
Is it webpack?

**Comment by TrySound** [comment]
And what is the target?

**Comment by TrySound** [comment]
@digitalkaoz Could you try to add `./` before paths in browser section? I probably missed this nuance.

**Comment by digitalkaoz** [comment]
Indeed that works! But why does the Browser section behave different than
the other sections?

Bogdan Chadkin <notifications@github.com> schrieb am Do., 4. Okt. 2018,
17:57:

**Comment by TrySound** [comment]
I don't know. Probably by spec.

**Comment by TrySound** [comment]
Perhaps this is done to be able to replace packages with another ones.

**Comment by TrySound** [comment]
Sent a fix
https://github.com/uber/react-map-gl/pull/610

**Comment by cigzigwon** [comment]
I'm guessing this is the reason my rollup component lib won't load the map? I'm making a compoennt lib consuming this lib and it will never load. You also need to implement the worker for mapbox-gl v2 or it won't compile correctly in webpack. I'm having trouble in rollup probably because the mapbox-gl lib should be a peer dep. I think no matter what I do I'm stuck.

**Pull request merged**
