### PR TITLE
Add props for bearing and pitch

### PR DESCRIPTION
**Pull request by jwarning**
Just a simple addition of optional props to set the bearing and pitch in the viewport.

### CODE REVIEW

**Comment by ibgreen** [comment]
@jwarning 
This is one of three pieces I am looking at for supporting "tilted view".
1) Adding support for these props and forwarding them to mapbox-gl (exactly as you have done in this PR!)
2) Add support for 3D navigation (event handling) and add the pitch/bearing props to the `onChangeViewport` callback. Haven't made final decision but perhaps a variant of `map-interactions.react.js`?
3) Calculate a projection transformation matrix from bearing and pitch (that matches the transformation matrix mapbox-gl calculates) and supply it to `onChangeViewport`, so that overlays can apply the same 3D transform as MapBoxGL does. 
About 3) I am not sure how practical setting 3D transforms is for the overlays that are included in react-map-gl. My use case is the WebGL based map overlays in [deck.gl](https://github.com/uber/deck.gl)

@vicapow - This covers #1 nicely. Happy to pull this.

**Comment by ibgreen** [comment]
@jwarning 
* For completeness, it would be nice to have a mention of these in the docs, maybe a note towards the end of README. 
* Also I think we will want to add an example that showcases these. It would become more elaborate as we do 2 and 3 on the list, but you could get it started, e.g. just hard coding bearing and pitch to non-zero constants for now.
Let me know what you think?

**Comment by vicapow** [comment]
I don't recommend merging these changes now as this will break how the viewport transformation code works during interaction when they're present.

**Comment by jwarning** [comment]
Fair enough. I realise that there are a couple other things which need to be done to make this more complete. Happy to potentially help on getting that sorted if need be.

**Comment by ibgreen** [comment]
>Fair enough. I realise that there are a couple other things which need to be done to make this more complete. Happy to potentially help on getting that sorted if need be.

@jwarning 
If you'd like to help you could try installing version 1.0.0-beta-5 (or pull the es6 branch) and let me know if any issues.
- MapGL now takes `pitch` and `bearing` props (per your PR)
- You can now enable tilt controls with `perspectiveMode={true}`. (using Command-drag)
- There is a new example with tilt so do `npm start` first after you pull and try Command-drag in the top example.
- In your own app, you do need to make sure that you pass the entire `mapState` from `onUpdateViewport` back into the component (there are new perspective related props in addition to `lat/lon/zoom/isDragging`)

**Comment by jwarning** [comment]
I'm having some issue compiling the new version for use in my project. I'm using a couple hacks to get it to build with webpack, however the new build seems to have new issues to work around. I'll try and see if I can figure a way to get it working though.

**Comment by ibgreen** [comment]
> Supporting webpack/browserify properly might be something worth investigating, as most people will consume this library with a tool like that.

@jwarning 
Thanks for the update. While I've never used webpack, I am consuming this internally in a browserify based production environment and I can confirm that it works well with browserify.

Would be interested to hear more about the `gl-matrix` issue. My first thought is that since this is an indirect dependency (`mapbox-gl-js` requires it), if webpack has issues with that it should probably be reported directly in either the `gl-matrix` or `mapbox-gl-js` repos, not sure `react-map-gl` can do anything except change the version of its `mapbox-gl-js` dependency if there is a version that fixes it.

Otherwise, I'd have thought that as long as webpack was directed to `react-map-gl`'s `dist/index.js` it would simply walk the require tree from there. Since all of `react-map-gl`'s ES6 code has been pre-transpiled to ES5 in the package.json prepublish hook, it should pose no problems for a mature JS bundler like webpack.

**Comment by jwarning** [comment]
Even despite using the transpiled files in dist/index.js, there are a couple other issues which arise from including some of react-map-gl's dependencies. The main one seems to be that the `shaders.js` file in `mapbox-gl` calls `'fs'` which cannot be included into a browser bundle. One can get around this with certain webpack loaders. See some of the solutions in [https://github.com/uber/react-map-gl/issues/21](https://github.com/uber/react-map-gl/issues/21).

**Pull request merged**
