### PR TITLE
[bug] set `componentWillUnmount` to `noop` along with `componentDidMount`

### PR DESCRIPTION
**Pull request by koulmomo**

### CODE REVIEW

**Comment by koulmomo** [comment]
I recently updated the library on an existing app and jenkins test started failing when unmounting a component.

The issue occurs because in certain cases `componentDidMount` which is the only thing that ever sets `this._mapbox` is set to noop (@see: https://github.com/uber/react-map-gl/blob/fe70f666448ddd9a84c306598fc3c261a1cb5343/src/components/static-map.js#L68)

but `componentWillUnmount` is always called.

**Comment by ibgreen** [comment]
> but componentWillUnmount is always called.

Got it. I'd prefer that this was fixed consistently, to make it as easy as possible for the various maintainers of this repo, i.e.:
* we should also set componentWillUnmount to `noop` 
* or we should check for mapbox in all cases.

I suggest the former for now as that seems to be the current approach.

**Comment by abmai** [comment]
Agree with @ibgreen's point on setting `componentWillUnmount` to `noop` as well in this case, because we're not initializing anything anyway.

@koulmomo what do you think about that solution?

**Comment by koulmomo** [comment]
@ibgreen @abmai implemented option 1

**Comment by abmai** [comment]
Thank you, @koulmomo!

**Pull request merged**
