### PR TITLE
Add project method to HTML Overlay

### PR DESCRIPTION
**Pull request by jwarning**
This adds in the same project method that the SVG Overlay and others have, such that one can correctly project elements inside an html overlay onto the map.

### CODE REVIEW

**Comment by jmccosh** [comment]
A polite bump on this one; we would really appreciate it if this PR could be merged.

**Comment by Apercu** [comment]
Hey, thanks! Do you mind sign the Uber CLA?

**Comment by jwarning** [comment]
@Apercu  Yeah sure, let me know how to go about that.

**Comment by Apercu** [comment]
@jwarning Thanks!

**Pull request merged**
