### PR TITLE
update mapbox-gl to v0.25.1

### PR DESCRIPTION
**Pull request by stepankuzmin**
Hi there! Mapbox GL v0.25.1 out on September 30 (https://github.com/mapbox/mapbox-gl-js/blob/master/CHANGELOG.md), all tests are passed, so maybe we can update to this version?

### CODE REVIEW

**Comment by cammanderson** [comment]
I think we have some issues merging this directly. Version 0.25 dropped support for webpack due to the ongoing webworkify issues. You now directly read in the dist files. This wouldn't be an issue for people using the mapbox API directly, but the utils/transform module in react-map-gl needs access to the mapbox GP class not exposed using the dist.

**Comment by stepankuzmin** [comment]
I see. So there is no way to use mapbox-gl 0.25 with react-gl-map if mapbox-gl is not exposing Transform class?

**Comment by cammanderson** [comment]
You could potentially do some trick with webpack I guess; alias the transform class import to the source? I'm a little stuck myself at the moment.

**Comment by cammanderson** [comment]
I think I managed to do it by running 1.6.0 react map gl, and setting up my webpack to call in the webpack dist, with another alias to the transform file directly. Works and compiles, testing across chrome etc. Yet to confirm if IE11 etc run..

**Comment by contra** [comment]
Should be closed, lib already updated to 0.26.0 https://github.com/uber/react-map-gl/blob/master/package.json#L29

**Comment by Apercu** [comment]
Thanks, closing as @contra mentioned.

**Pull request closed without merging**
