### PR TITLE
Add require example directly in readme

### PR DESCRIPTION
**Pull request by mdamien**
makes the copy paste easier

also, looks like you need an API token, maybe should put it in the readme/doc too ?

### CODE REVIEW

**Comment by vicapow** [comment]
Hey @mdamien, thanks for the PR! Before I can merge, could you sign our Contributor License Agreement (CLA)? You can find the [link here](https://docs.google.com/a/uber.com/forms/d/1pAwS_-dA1KhPlfxzYLBqK6rsSWwRwH95OCCZrcsY5rk/viewform). You only need to sign it once for all Uber projects.

I think the README already mentioned the Mapbox API token (for map styles that use Mapbox's API's). See: https://github.com/uber/react-map-gl/blame/master/README.md#L110 Do you think we should go into more detail or call it out more?

**Comment by mdamien** [comment]
For the API token, it's just required my mapbox gl by default: https://github.com/mapbox/mapbox-gl-js/blob/b7032636206448e16eb681836f97e79f0587fd7e/js/util/config.js

Enforced here: https://github.com/mapbox/mapbox-gl-js/blob/master/js/util/mapbox.js#L9

But you make the props no required to indicate that it's only for custom styles: https://github.com/uber/react-map-gl/blob/master/src/map.react.js#L105

So, for now, mounting the component without a token throws an exception.

Maybe have another PR to make it required or something.

Signed the CLA, should be ok.

**Comment by vicapow** [comment]
@mdamien I see your point. It is a little confusing that we use a Mapbox style by default but don't require the access token from within MapGL. With that said, there are lots of use cases where a user doesn't need to have a Mapbox API token since they're not using Mapbox's services. One example of this is when using Stamen's base tiles: https://github.com/vicapow/react-map-gl-heatmap-overlay/blob/master/example/main.js#L15. In the case where we're using a map style that relies on Mapbox services, I think we should continue to rely on MapboxGL-js to throw an error.

**Comment by mdamien** [comment]
ok, looks good to me :smile_cat:

**Pull request merged**
