### PR TITLE
Dev 0.29

### PR DESCRIPTION
**Pull request by ibgreen**
Reopening towards dev

@abmai - Trying to merge mapbox 0.29 into webpack based dev branch - ran into trouble with the transform.js dependency - the mapbox code base now uses flow syntax in their JavaScript so our practice of hand-importing selected source files (instead of their prebuilt "bundle") causes problems in non-browserify based workflows.

### CODE REVIEW

**Comment by ibgreen** [comment]
> hmm. why would this be webpack specific? 

My data is partly based on mapbox's own comments in [mapbox-gl-js README](https://github.com/mapbox/mapbox-gl-js#using-mapbox-gl-js-with-other-module-systems), and partly based on the issues we have been hearing from our react-map-gl users trying to use mapbox-gl with non-browserify environments.

> perhaps 2.0 is also a good time for us to experiment with flow in our codebase as well - would that help here?

Yes should be a good discussion. As for my starting point, I'm 100% for flow **in comments**. But I'm not excited about adding more non-standard syntax to our JavaScript. 

Adding more non-standard syntax would go against the cleanup I did here the last few days, removing non-ES6 constructs and replacing trivial uses of JSX with `createElement`. In fact, as of today, on the dev branch in this repo, the babel transpiler is no longer even installed, and the tests run under Node 6+ as raw, untranspiled ES6. If we put in flow syntax, that would likely have to be reversed.

**Comment by abmai** [comment]
I am at my wit's ends for the night with this. Adding the `remove-flow-types-loader` works for bundling + running examples but doesn't work for tests. Tried to do something smart with `externals` (let webpack include the mapbox-gl js utils in our bundle) but still run into the same flow annotation error.

Will try again at some point tomorrow. In mean time, they also released 0.30 so I'll probably look into pushing us there on master as well.

**Comment by abmai** [comment]
My changes are up on the `dev029` branch if you want to take a look.

**Comment by ibgreen** [comment]
>Adding the remove-flow-types-loader works for bundling + running examples but doesn't work for tests.

@abmai 

- The tests fail because the tests are currently set up to run without transpilation (i.e. they run as ES6 code)

- If we don't care about that, the easiest way is probably to create a second webpack config file for bundling a full test suite (with all dependencies, as opposed to just bundling the library files). deck.gl dev does this for running tests in the browser.

- Another concern is that this solution pushes the burden of applying the `remove-flow-type-transform` to the app (your example shows this) which doesn't feel great.

- As an alternative, I started playing with including the "deflowed" transform.js in the output bundle, but didn't get all the way. Setting it up so that the consuming app doesn't need to fiddle with `resolves` would also be desirable.

- Ultimately, we should another push on removing the need for directly importing `transform`. We are almost there...

**Comment by abmai** [comment]
There are a few choices, but I think our solution here depends on the last point - whether we see ourselves continuing to use their `Transform` class which isn't officially supported for public use.

I tried doing your third point as well (fiddling with `externals` so that `mapbox-gl/js/geo` and `mapbox-gl/js/util` are bundled (and therefore stripped of flow syntax) to no avail yet.

Another option here is to have a separate webpack config just for tests - which might be desirable just to keep the two environment more separate.

**Pull request closed without merging**
