### PR TITLE
Upgrade D3 to version 4

### PR DESCRIPTION
**Pull request by samhogg**
Here's an initial cut at #34

* Used d3 modules where appropriate
* Added round function to utils, d3@4 doesn't have it yet
* TODO - find a replacement for d3.geo in choropleth.react.js
  This might be coming soon - although https://github.com/d3/d3-geo
  is currently empty.
* TODO - use alphaify from `npm` rather than my fork [(relies on this PR being merged)](https://github.com/vicapow/alphaify/pull/1)

Obviously the d3.geo part is a blocker at the moment, but the other changes are pretty straightforward.

### CODE REVIEW

**Comment by vicapow** [comment]
This is lookin great, @samhogg. I guess we should wait on the geo stuff before landing this

**Comment by mcnuttandrew** [comment]
Looks like the geo stuff is up and running, i think the commented out lines can be replaced with with

`      const transform = geoTransform({point: projectPoint});
      const path = geoPath().projection(transform).context(ctx);`

**Comment by samhogg** [comment]
@vicapow - I have some bandwidth to have another go at this later in the week if that's helpful

**Comment by vicapow** [comment]
@samhogg that would be awesome! Might need to rebase from master. I think there's been a few changes

**Comment by samhogg** [comment]
@vicapow yeah the d3 module dependencies have moved significantly too. Will have a shot and get back to you later in the week.

**Comment by ibgreen** [comment]
This has been resolved separately, see latest master. Apologies for not using this PR, this became part of a larger dependency cleanup effort.

**Pull request closed without merging**
